apiVersion: v2
name: rune-ui
description: A Helm chart for the RUNE UI (The Face of the RUNE ecosystem)
type: application
version: 0.0.0-a0
appVersion: "0.0.0-a0"
keywords:
  - rune
  - ui
  - llm
  - benchmark
  - kubernetes
license: Apache-2.0
maintainers:
  - name: lpasquali
    email: luca.pasquali@example.com
