#!/usr/bin/env python3
"""Sync an upstream image tag into rune-charts tracked files.

Reads IMAGE_NAME, IMAGE_TAG, SOURCE_REPO from environment variables.
Updates .ci/upstream-images.env and relevant chart values.yaml files.
"""
from pathlib import Path
import os
import re
from datetime import datetime, timezone

image_name = os.environ["IMAGE_NAME"].strip()
image_tag = os.environ["IMAGE_TAG"].strip()
source_repo = os.environ["SOURCE_REPO"].strip()

env_path = Path('.ci/upstream-images.env')
env_path.parent.mkdir(parents=True, exist_ok=True)

kv = {}
if env_path.exists():
    for line in env_path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        k, v = line.split('=', 1)
        kv[k.strip()] = v.strip()

full_ref = f"{image_name}:{image_tag}"
if image_name.endswith('/rune'):
    kv['RUNE_IMAGE'] = full_ref
elif image_name.endswith('/rune-operator'):
    kv['RUNE_OPERATOR_IMAGE'] = full_ref
else:
    kv['UPSTREAM_IMAGE'] = full_ref

kv['LAST_SYNC_SOURCE_REPO'] = source_repo
kv['LAST_SYNC_AT_UTC'] = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')

ordered_keys = [
    'RUNE_IMAGE',
    'RUNE_OPERATOR_IMAGE',
    'UPSTREAM_IMAGE',
    'LAST_SYNC_SOURCE_REPO',
    'LAST_SYNC_AT_UTC',
]
lines = [
    '# Auto-generated by sync-upstream-images workflow. Do not edit manually.'
]
for key in ordered_keys:
    if key in kv:
        lines.append(f"{key}={kv[key]}")
for key in sorted(k for k in kv.keys() if k not in ordered_keys):
    lines.append(f"{key}={kv[key]}")
env_path.write_text("\n".join(lines) + "\n", encoding='utf-8')

# If this is the RUNE API image, update chart default image.tag.
if image_name.endswith('/rune'):
    values_path = Path('charts/rune/values.yaml')
    if values_path.exists():
        content = values_path.read_text(encoding='utf-8')
        updated = re.sub(r'^  tag:\s*".*"\s*$', f'  tag: "{image_tag}"', content, count=1, flags=re.MULTILINE)
        values_path.write_text(updated, encoding='utf-8')

# If this is the operator image, update operator chart default image.tag.
if image_name.endswith('/rune-operator'):
    op_values_path = Path('charts/rune-operator/values.yaml')
    if op_values_path.exists():
        content = op_values_path.read_text(encoding='utf-8')
        updated = re.sub(r'^  tag:\s*".*"\s*$', f'  tag: "{image_tag}"', content, count=1, flags=re.MULTILINE)
        op_values_path.write_text(updated, encoding='utf-8')
