{{- if .Values.githubToken.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.githubToken.secretName | default (printf "%s-token" (include "rune-audit.fullname" .)) }}
  labels:
    {{- include "rune-audit.labels" . | nindent 4 }}
type: Opaque
data:
  github-token: {{ .Values.githubToken.token | b64enc | quote }}
{{- end }}
