{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rune-audit.serviceAccountName" . }}
  labels:
    {{- include "rune-audit.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
<<<<<<< HEAD
=======
automountServiceAccountToken: false
>>>>>>> 9948934 (feat: add Helm chart for rune-audit CronJob deployment)
{{- end }}
