apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rune.fullname" . }}
  labels:
    {{- include "rune.labels" . | nindent 4 }}
data:
  RUNE_BACKEND: {{ .Values.rune.backend | quote }}
  RUNE_API_HOST: {{ .Values.rune.api.host | quote }}
  RUNE_API_PORT: {{ .Values.rune.api.port | quote }}
  RUNE_API_TENANT: {{ .Values.rune.api.tenant | quote }}
  RUNE_API_AUTH_DISABLED: {{ .Values.rune.api.authDisabled | quote }}
  RUNE_DEBUG: {{ .Values.rune.debug | quote }}
  RUNE_VASTAI: {{ .Values.rune.vastai.enabled | quote }}
  RUNE_VASTAI_TEMPLATE: {{ .Values.rune.vastai.template | quote }}
  RUNE_VASTAI_MIN_DPH: {{ .Values.rune.vastai.minDph | quote }}
  RUNE_VASTAI_MAX_DPH: {{ .Values.rune.vastai.maxDph | quote }}
  RUNE_VASTAI_RELIABILITY: {{ .Values.rune.vastai.reliability | quote }}
  RUNE_VASTAI_STOP_INSTANCE: {{ .Values.rune.vastai.stopInstance | quote }}
  RUNE_OLLAMA_URL: {{ .Values.rune.ollama.url | quote }}
  RUNE_OLLAMA_WARMUP: {{ .Values.rune.ollama.warmup | quote }}
  RUNE_OLLAMA_WARMUP_TIMEOUT: {{ .Values.rune.ollama.warmupTimeout | quote }}
  RUNE_QUESTION: {{ .Values.rune.question | quote }}
  RUNE_MODEL: {{ .Values.rune.model | quote }}
