apiVersion: v2
name: rune-operator
description: Helm chart for the RUNE Kubernetes operator
type: application
version: 0.0.0-a0
appVersion: "0.0.0-a0"
keywords:
  - rune
  - operator
  - benchmarking
home: https://github.com/lpasquali/rune-operator
sources:
  - https://github.com/lpasquali/rune-operator
license: Apache-2.0
maintainers:
  - name: lpasquali
