# SPDX-License-Identifier: Apache-2.0
name: Release Charts

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: lpasquali/rune-ci/.github/workflows/helm-release.yml@v0.1.0
    with:
      charts-dir: "charts"
