# SPDX-License-Identifier: Apache-2.0
name: Release Charts

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: lpasquali/rune-ci/.github/workflows/helm-release.yml@ac0bd4bc0253ee0261c2e2e63034aa2d7d903e5e # v0.1.0
    with:
      charts-dir: "charts"
