# SPDX-License-Identifier: Apache-2.0
name: Release Charts

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: lpasquali/rune-ci/.github/workflows/helm-release.yml@cfdb81c2d4f03bb82786729401fe7b8e833e4347
    with:
      charts-dir: "charts"
